# 1. server port
server:
  port: 8080

# 2. spring config
spring:
  application:
    name: discodeit

  # 2-1. database connection info config
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  # 2-2. jpa config
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  # 2-3. servlet config
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

# 3. logging config
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# 4. custom config (discodeit 전용 설정)
discodeit:
  storage:
    type: local        #
    local:
      root-path: ./storage_data  # 실제 파일이 저장될 폴더 경로입니다.