spring:
  datasource:
    url: jdbc:postgresql://your-real-db-server:5432/discodeit
  jpa:
    hibernate:
      ddl-auto: validate # 요구사항: 운영은 안전하게 validate

logging:
  level:
    com.sprint.mission.discodeit: info # 요구사항: 운영 환경은 info