name: CI - Test

# main 브랜치에 Pull Request가 생성될 때 실행
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 자바 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. 빌드 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 테스트 실행
      - name: Run tests with Gradle
        run: ./gradlew test
        env:
          DISCODEIT_STORAGE_S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          DISCODEIT_STORAGE_S3_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          DISCODEIT_STORAGE_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          DISCODEIT_STORAGE_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}